main:
P3_1: main
	g++ -g P3_1.cpp
	./a.out Test/Test1
	./a.out Test/Test2
	./a.out Test/Test3
P3_2: main
	g++ -g P3_2.cpp
	./a.out Boat/img1
	./a.out Boat/img3
	./a.out Boat/img5
	./a.out Graf/img1
	./a.out Graf/img3
	./a.out Graf/img5